###
GET https://eduallserver.eduallsys.com

###
GET https://goldpetserver.vercel.app/htmarketgetallproducts

###
POST http://localhost:6500/htmarketregisternewproduct
content-type: application/json

{
    "name": "Secadores de adsorção modulares ADM-DRY com tempo de ciclo fixo controlado, pré e pós-filtros pré-instalados, fluxo volumétrico de até 1,5 m3/min", 
    "price":null,
    "oldprice":null, 
    "description":"Os secadores refrigerados da série RDX com capacidade de 0,4-36,0 m3/min são equipados com um eficiente trocador de calor em alumínio fundido e um separador de coalescência integrado. O baixo grau de perda de pressão devido ao separador incorporado e ao isolamento externo confiável do trocador de calor facilitam um alto nível de eficiência energética para o sistema. O separador coalescente é insensível a flutuações de pressão no caso de carga variável e remove de forma confiável até 98% da umidade condensada.",
    "category":"665f0704895b0ecccf8ef0ab", 
    "subcategorie":"",
    "brand":"comprag",
    "serie":"667153a8f3c0c102f638b521",
    "code":0,  
    "stockamount":34
} 


###
POST http://localhost:6500/htmarketuploadimages
content-type: application/json

{
    "name": "https://www.comprag.com/en/comprag/img_pop/11_rdx.jpg", 
    "code":"66719327a7f181ae175393f3" 
} 




###
POST http://localhost:6500/htmarketregisternewproductserie
content-type: application/json

{
    "name": "RDX", 
    "subcategorie":"665f0691895b0ecccf8ef0a1" 
} 


 

###
POST http://localhost:6500/htmarketregisternewcategorie
content-type: application/json

{
    "name": "Equipamentos"
} 


###
POST http://localhost:6500/htmarketregisternewsubcategorie
content-type: application/json

{
    "name": " ", 
    "categorie":"665f0a59895b0ecccf8ef0bd"
} 