###
GET https://eduallserver.eduallsys.com

###
DELETE https://goldpetserver.vercel.app/htmarketdeleteproduct/66853cfe72d1339d1e3c16a7

###
POST http://localhost:6500/htmarketregisternewproduct
content-type: application/json

{
    "name": "Secadores de adsorção ADX-F com tempo de ciclo fixo controlado com pré e pós-filtros instalados, capacidade até 25,0 m3/min", 
    "price":null,
    "oldprice":null, 
    "description":"Os secadores de adsorção Comprag funcionam em seu ponto ideal de trabalho com uma duração de ciclo de 10 minutos. A redução do número de ciclos de sopro de desidratação reduz a carga operacional nos receptores, válvulas e dessecante. Além disso, um ciclo longo reduz a perda de pressão do ar durante a restauração da pressão operacional no receptor após um ciclo de regeneração. Um ciclo de secagem de dois minutos utilizando ar comprimido seco para purgar a coluna que está sendo regenerada consome momentaneamente cerca de 7,5% do ar comprimido seco. Os secadores por adsorção Comprag ADX funcionando em um ciclo de dez minutos usam, em média, apenas cerca de 1% da quantidade total de ar purificado.",
    "category":"665f0704895b0ecccf8ef0ab", 
    "subcategorie":"",
    "brand":"comprag",
    "serie":"667153a8f3c0c102f638b521",
    "code":0,  
    "stockamount":34
} 


###
POST http://localhost:6500/htmarketuploadimages
content-type: application/json

{
    "name": "https://www.comprag.com/en/comprag/img_pop/02_wos.jpg", 
    "code":"667acca0d8db2c4d24dae4af" 
} 


###
GET  https://htmarketserver.vercel.app/htmarketgetallproducts




###
POST http://localhost:6500/htmarketregisternewproductserie
content-type: application/json

{
    "name": "Série N/EN", 
    "subcategorie":"668282539237c336e3de3865" 
} 


 

###
POST http://localhost:6500/htmarketregisternewcategorie
content-type: application/json

{
    "name": "acopladoras"
} 


###
POST http://localhost:6500/htmarketregisternewsubcategorie
content-type: application/json

{
    "name": "Braçadeira de sela",
    "categorie": "665f0a59895b0ecccf8ef0bd"
} 

###
POST http://localhost:6500/htmarketlogin
content-type: application/json

{
    "email": "kiossocamueg@gmail.com", 
    "password":"12345678"
} 